export const trainCategoryShortNames = {
    "regionale": "REG",
    "regionale veloce": "RV",
    "regio express": "RE",
    "frecciarossa": "FR",
    "frecciabianca": "FB",
    "eurocity": "EC",
    "railjet": "RJ",
    "intercity": "IC",
    "italo": "AV",
    "intercity notte": "ICN",
    "malpensa express": "MXP",
    "metropolitano": "M",
    "espresso": "E",
    "eurostar italia": "ES*",
    "autocorsa": "Bus",
    "treno storico": "TS",
    "interregionale": "iR",
}
