export const trainCategoryShortNames = {
    "regionale": "R",
    "regionale veloce": "RV",
    "regio express": "RE",
    "frecciarossa": "FR",
    "frecciabianca": "FB",
    "eurocity": "EC",
    "railjet": "RJ",
    "intercity": "IC",
    "italo": "AV",
    "intercity notte": "ICN",
    "malpensa express": "MXP",
    "metropolitano": "M",
    "espresso": "EXP",
    "eurostar italia": "ES*",
    "autocorsa": "bus",
    "treno storico": "TS",
    "interregionale": "iR",
}

export const trainCategoryLongNames = {
    "R": "Regionale",
    "REG": "Regionale",
    "RV": "Regionale Veloce",
    "RE": "Regio Express",
    "FR": "Frecciarossa",
    "FB": "Frecciabianca",
    "EC": "Eurocity",
    "RJ": "Railjet",
    "IC": "Intercity",
    "AV": "Alta Velocità",
    "ICN": "Intercity Notte",
    "MXP": "Malpensa Express",
    "M": "Metropolitano",
    "EXP": "Espresso",
    "iR": "Interregionale",
}
